server:
  port: 9002
spring:
  application:
    name: hrm-page
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_page 
      username: root
      password: 1017
mybatis-plus:
  mapper-locations: classpath:com/lixuelian/hrm/mapper/*Mapper.xml
  type-aliases-package: com.lixuelian.hrm.domain,com.lixuelian.hrm.query